[package]
name = "python"
version = "0.1.15"
edition = "2021"

[lib]
name = "amazing_calc"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.16.5", features = ["extension-module"] }
amazing_calc = { path = "../amazing_calc" }

[package.metadata.maturin]

python-source = "pysrc"
