[package]
name = "python"
version = "0.1.12"
edition = "2021"

[lib]
name = "amazing_calc"
crate-type = ["cdylib"]

[dependencies]
cpython = "0.7"
amazing_calc = { path = "../amazing_calc" }

[package.metadata.maturin]

python-source = "pysrc"
