name: Test build Python packages

on: [push]
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python: ["3.7", "3.8", "3.9", "3.10"]
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        # TODO: arch is not supported yet (arm64, i386, x86_64, ...)

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "${{ matrix.python }}"
          cache: "pipenv"

      - name: Install build dependencies
        run: |
          cd python
          pipx install pipenv
          pipenv sync --dev

      - name: packaging
        run: |
          cd python
          pipenv run build --release --strip --interpreter python${{ matrix.python }}
